### ISSUE TITLE
CommsExamples don't build with v10.4.0

### ISSUE THREAD

**Issue by kyrofa** [themoos/examples-docs-moos#1]
Looks like the API has changed, the build fails with several errors like the following:

```
examples-docs-moos/docs/examples/CommsExamples/EX40/ex40.cpp:70:8: error: ‘class MOOS::MOOSAsyncCommClient’ has no member named ‘AddMessageCallback’; did you mean ‘AddMessageCallBack’?
  Comms.AddMessageCallback("callback_Y","Y",funcY,NULL);
```
